import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { mergeConfig, defineConfig, configDefaults } from 'vitest/config'
import viteConfig from './vite.config'

const resolveFromRoot = (relativePath: string) => path.resolve(__dirname, relativePath)

const legacyTestAliases = [
  { find: /^@\/api\/auth$/, replacement: resolveFromRoot('./src/features/auth/api/auth.ts') },
  { find: /^@\/api\/account$/, replacement: resolveFromRoot('./src/features/master-data/accounts/api/account.ts') },
  { find: /^@\/api\/category$/, replacement: resolveFromRoot('./src/features/master-data/categories/api/category.ts') },
  { find: /^@\/api\/customer$/, replacement: resolveFromRoot('./src/features/master-data/customers/api/customer.ts') },
  { find: /^@\/api\/dashboard$/, replacement: resolveFromRoot('./src/features/dashboard/api/dashboard.ts') },
  { find: /^@\/api\/import$/, replacement: resolveFromRoot('./src/features/import/api/import.ts') },
  { find: /^@\/api\/payable$/, replacement: resolveFromRoot('./src/features/finance/api/payable.ts') },
  { find: /^@\/api\/person$/, replacement: resolveFromRoot('./src/features/master-data/persons/api/person.ts') },
  { find: /^@\/api\/project$/, replacement: resolveFromRoot('./src/features/master-data/projects/api/project.ts') },
  { find: /^@\/api\/receivable$/, replacement: resolveFromRoot('./src/features/finance/api/receivable.ts') },
  { find: /^@\/api\/rule$/, replacement: resolveFromRoot('./src/features/reconciliation/api/rule.ts') },
  { find: /^@\/api\/supplier$/, replacement: resolveFromRoot('./src/features/master-data/suppliers/api/supplier.ts') },
  { find: /^@\/api\/transaction$/, replacement: resolveFromRoot('./src/features/transactions/api/transaction.ts') },
  { find: /^@\/views\/Dashboard\.vue$/, replacement: resolveFromRoot('./src/features/dashboard/pages/DashboardPage.vue') },
  { find: /^@\/views\/Login\.vue$/, replacement: resolveFromRoot('./src/features/auth/pages/LoginPage.vue') },
  { find: /^@\/views\/categories\/CategoryForm\.vue$/, replacement: resolveFromRoot('./src/features/master-data/categories/components/CategoryForm.vue') },
  { find: /^@\/views\/categories\/CategoryList\.vue$/, replacement: resolveFromRoot('./src/features/master-data/categories/pages/CategoryListPage.vue') },
  { find: /^@\/views\/customers\/CustomerDetail\.vue$/, replacement: resolveFromRoot('./src/features/master-data/customers/pages/CustomerDetailPage.vue') },
  { find: /^@\/views\/customers\/CustomerForm\.vue$/, replacement: resolveFromRoot('./src/features/master-data/customers/pages/CustomerFormPage.vue') },
  { find: /^@\/views\/customers\/CustomerList\.vue$/, replacement: resolveFromRoot('./src/features/master-data/customers/pages/CustomerListPage.vue') },
  { find: /^@\/views\/finance\/FinanceManagement\.vue$/, replacement: resolveFromRoot('./src/features/finance/pages/FinanceManagementPage.vue') },
  { find: /^@\/views\/import\/ImportPage\.vue$/, replacement: resolveFromRoot('./src/features/import/pages/ImportPage.vue') },
  { find: /^@\/views\/payables\/PayableDetail\.vue$/, replacement: resolveFromRoot('./src/features/finance/pages/PayableDetailPage.vue') },
  { find: /^@\/views\/payables\/PayableList\.vue$/, replacement: resolveFromRoot('./src/features/finance/pages/PayableListPage.vue') },
  { find: /^@\/views\/persons\/PersonForm\.vue$/, replacement: resolveFromRoot('./src/features/master-data/persons/pages/PersonFormPage.vue') },
  { find: /^@\/views\/persons\/PersonList\.vue$/, replacement: resolveFromRoot('./src/features/master-data/persons/pages/PersonListPage.vue') },
  { find: /^@\/views\/projects\/ProjectDetail\.vue$/, replacement: resolveFromRoot('./src/features/master-data/projects/pages/ProjectDetailPage.vue') },
  { find: /^@\/views\/projects\/ProjectForm\.vue$/, replacement: resolveFromRoot('./src/features/master-data/projects/pages/ProjectFormPage.vue') },
  { find: /^@\/views\/projects\/ProjectList\.vue$/, replacement: resolveFromRoot('./src/features/master-data/projects/pages/ProjectListPage.vue') },
  { find: /^@\/views\/receivables\/ReceivableDetail\.vue$/, replacement: resolveFromRoot('./src/features/finance/pages/ReceivableDetailPage.vue') },
  { find: /^@\/views\/receivables\/ReceivableList\.vue$/, replacement: resolveFromRoot('./src/features/finance/pages/ReceivableListPage.vue') },
  { find: /^@\/views\/rules\/RuleForm\.vue$/, replacement: resolveFromRoot('./src/features/reconciliation/components/RuleForm.vue') },
  { find: /^@\/views\/rules\/RuleList\.vue$/, replacement: resolveFromRoot('./src/features/reconciliation/pages/RuleListPage.vue') },
  { find: /^@\/views\/suppliers\/SupplierForm\.vue$/, replacement: resolveFromRoot('./src/features/master-data/suppliers/pages/SupplierFormPage.vue') },
  { find: /^@\/views\/suppliers\/SupplierList\.vue$/, replacement: resolveFromRoot('./src/features/master-data/suppliers/pages/SupplierListPage.vue') },
  { find: /^@\/views\/transactions\/TransactionDetail\.vue$/, replacement: resolveFromRoot('./src/features/transactions/pages/TransactionDetailPage.vue') },
  { find: /^@\/views\/transactions\/TransactionList\.vue$/, replacement: resolveFromRoot('./src/features/transactions/pages/TransactionListPage.vue') },
  { find: /^@\/components\/ImportDialog\.vue$/, replacement: resolveFromRoot('./src/features/import/components/ImportDialog.vue') },
  { find: /^@\/components\/MaturityAlert\.vue$/, replacement: resolveFromRoot('./src/features/system/components/MaturityAlert.vue') },
  { find: /^@\/components\/SearchableFilterInput\.vue$/, replacement: resolveFromRoot('./src/shared/ui/SearchableFilterInput.vue') },
  { find: /^@\/components\/SearchableInput\.vue$/, replacement: resolveFromRoot('./src/shared/ui/SearchableInput.vue') },
  { find: /^@\/components\/SearchableSelect\.vue$/, replacement: resolveFromRoot('./src/shared/ui/SearchableSelect.vue') },
  { find: /^@\/components\/tags\/TagSelector\.vue$/, replacement: resolveFromRoot('./src/components/tags/TagSelector.vue') },
  { find: /^@\/stores\/user$/, replacement: resolveFromRoot('./src/features/auth/stores/user.ts') },
  { find: /^@\/constants\/colors$/, replacement: resolveFromRoot('./src/shared/constants/colors.ts') },
  { find: /^@\/constants\/table$/, replacement: resolveFromRoot('./src/shared/constants/table.ts') },
  { find: /^@\/composables\/useConfirm$/, replacement: resolveFromRoot('./src/shared/composables/useConfirm.ts') },
  { find: /^@\/composables\/useResizableTableColumns$/, replacement: resolveFromRoot('./src/shared/composables/useResizableTableColumns.ts') },
  { find: /^@\/layouts\/MainLayout\.vue$/, replacement: resolveFromRoot('./src/shared/layouts/MainLayout.vue') },
  { find: /^@\/types\/category$/, replacement: resolveFromRoot('./src/features/master-data/categories/types/category.ts') },
  { find: /^@\/types\/customer$/, replacement: resolveFromRoot('./src/features/master-data/customers/types/customer.ts') },
  { find: /^@\/types\/person$/, replacement: resolveFromRoot('./src/features/master-data/persons/types/person.ts') },
  { find: /^@\/types\/rule$/, replacement: resolveFromRoot('./src/features/reconciliation/types/rule.ts') },
  { find: /^@\/types\/supplier$/, replacement: resolveFromRoot('./src/features/master-data/suppliers/types/supplier.ts') },
  { find: /^@\/types\/transaction$/, replacement: resolveFromRoot('./src/features/transactions/types/transaction.ts') },
  { find: /^@\/utils\/request$/, replacement: resolveFromRoot('./src/shared/utils/request.ts') },
]

export default mergeConfig(
  viteConfig,
  defineConfig({
    resolve: {
      alias: [
        ...legacyTestAliases,
        { find: '@tests', replacement: resolveFromRoot('./tests') },
        { find: '@', replacement: resolveFromRoot('./src') },
      ],
    },
    test: {
      environment: 'happy-dom',
      exclude: [...configDefaults.exclude, 'e2e/**'],
      include: ['tests/**/*.test.ts'],
      root: fileURLToPath(new URL('./', import.meta.url)),
      globals: true,
      setupFiles: ['./tests/setup.ts'],
      coverage: {
        provider: 'v8',
        reporter: ['text', 'json', 'html'],
        exclude: [
          'node_modules/',
          'tests/',
          '**/*.d.ts',
          '**/*.config.*',
          '**/mockData',
          'dist/',
          'src/api/generated/**',
        ],
      },
    },
  }),
)
